package com.ncode.invoice.doa;
// Generated 12 Aug, 2017 10:35:23 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Transient;

/**
 * DirectpayInvoiceMail generated by hbm2java
 */
@Entity
@Table(name = "directpay_Invoice_mail")
public class DirectpayInvoiceMail implements java.io.Serializable {

    private int srno;
    private int invoiceNo;
    private Date invoiceDate;
    private String pdfYn;
    private String sendmailYn;
    private String toEmail;
    private String bccEmail;
    private int customer_id;

    public DirectpayInvoiceMail() {
    }

    public DirectpayInvoiceMail(int srno) {
        this.srno = srno;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "srno", unique = true, nullable = false)
    public int getSrno() {
        return this.srno;
    }

    public void setSrno(int srno) {
        this.srno = srno;
    }

    @Column(name = "invoice_no")
    public int getInvoiceNo() {
        return this.invoiceNo;
    }

    public void setInvoiceNo(int invoiceNo) {
        this.invoiceNo = invoiceNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "invoice_date", length = 23)
    public Date getInvoiceDate() {
        return this.invoiceDate;
    }

    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }

    @Column(name = "pdf_yn", length = 1)
    public String getPdfYn() {
        return this.pdfYn;
    }

    public void setPdfYn(String pdfYn) {
        this.pdfYn = pdfYn;
    }

    @Column(name = "sendmail_yn", length = 1)
    public String getSendmailYn() {
        return this.sendmailYn;
    }

    public void setSendmailYn(String sendmailYn) {
        this.sendmailYn = sendmailYn;
    }

    @Column(name = "to_email", length = 500)
    public String getToEmail() {
        return this.toEmail;
    }

    public void setToEmail(String toEmail) {
        this.toEmail = toEmail;
    }

    @Column(name = "bcc_email", length = 500)
    public String getBccEmail() {
        return this.bccEmail;
    }

    public void setBccEmail(String bccEmail) {
        this.bccEmail = bccEmail;
    }

    @Column(name = "customer_id")
    public int getCustomer_id() {
        return customer_id;
    }

    public void setCustomer_id(int customer_id) {
        this.customer_id = customer_id;
    }

}
